### ISSUE TITLE
Solving using POMCP

### ISSUE THREAD

**Issue by pparmesh** [JuliaPOMDP/DroneSurveillance.jl#17]
Hi,
I'm trying to solve the example problem using POMCP but it looks like its generating no policy. I'm new to using Julia and the POMDP repository in general. Is there some solver setting that I'm missing?

**Comment by MaximeBouton** [comment]
It is a bit hard to help without a minimum code to start with. Since this is not a bug per se, maybe start a discussion and provide a minimum example so we can help you https://github.com/JuliaPOMDP/POMDPs.jl/discussions
